#!/bin/bash -

i=0
cat $1 | while read line ; do
let i+=1
echo "cd $PWD/$line$2"
echo "cp ../processLaneSingleGTFParam ../$3 ./"
echo "./processLaneSingleGTFParam "$line".fasta.gz $line$2 $3 $4$i $5 $6 $7 $8"
echo "pwd"
done
